export const HOMEPAGE_TONE_STATE_ORDER = ['theta', 'alpha', 'delta', 'beta', 'gamma'];

export const HOMEPAGE_STATE_TONES = [
  {
    id: 'homepage-theta-drift',
    name: 'Theta Drift',
    shortLabel: 'Theta Drift',
    state: 'theta',
    targetState: 'theta',
    targetHz: 5.2,
    baseFreqHz: 192,
    durationSec: 60,
    summary: 'A bare theta binaural tone for imagery, meditation, and liminal settling.',
    description: 'A bare theta binaural tone for imagery, meditation, and liminal settling.',
    sourceType: 'homepage-generated',
    source_type: 'homepage-generated',
    modeLabel: 'Pure binaural state tone',
    wavUrl: '/audio/homepage-state-tones/theta-drift.wav',
    wav_url: '/audio/homepage-state-tones/theta-drift.wav',
    webmUrl: null,
    webm_url: null,
    mp3Url: null,
    mp3_url: null,
    target_hz: 5.2,
    target_state: 'theta',
    base_freq_hz: 192,
    duration_sec: 60
  },
  {
    id: 'homepage-alpha-focus',
    name: 'Alpha Focus',
    shortLabel: 'Alpha Focus',
    state: 'alpha',
    targetState: 'alpha',
    targetHz: 10,
    baseFreqHz: 220,
    durationSec: 60,
    summary: 'A bare alpha binaural tone for calm concentration and clean mental presence.',
    description: 'A bare alpha binaural tone for calm concentration and clean mental presence.',
    sourceType: 'homepage-generated',
    source_type: 'homepage-generated',
    modeLabel: 'Pure binaural state tone',
    wavUrl: '/audio/homepage-state-tones/alpha-focus.wav',
    wav_url: '/audio/homepage-state-tones/alpha-focus.wav',
    webmUrl: null,
    webm_url: null,
    mp3Url: null,
    mp3_url: null,
    target_hz: 10,
    target_state: 'alpha',
    base_freq_hz: 220,
    duration_sec: 60
  },
  {
    id: 'homepage-delta-rest',
    name: 'Delta Rest',
    shortLabel: 'Delta Rest',
    state: 'delta',
    targetState: 'delta',
    targetHz: 2.8,
    baseFreqHz: 108,
    durationSec: 60,
    summary: 'A bare delta binaural tone for deep rest, downshifting, and recovery.',
    description: 'A bare delta binaural tone for deep rest, downshifting, and recovery.',
    sourceType: 'homepage-generated',
    source_type: 'homepage-generated',
    modeLabel: 'Pure binaural state tone',
    wavUrl: '/audio/homepage-state-tones/delta-rest.wav',
    wav_url: '/audio/homepage-state-tones/delta-rest.wav',
    webmUrl: null,
    webm_url: null,
    mp3Url: null,
    mp3_url: null,
    target_hz: 2.8,
    target_state: 'delta',
    base_freq_hz: 108,
    duration_sec: 60
  },
  {
    id: 'homepage-delta-cognistration-anchor',
    name: 'Cognistration Delta Anchor',
    shortLabel: 'Delta Anchor',
    state: 'delta',
    targetState: 'delta',
    targetHz: 2.6,
    baseFreqHz: 112,
    durationSec: 60,
    summary: 'A Cognistration delta binaural tone for grounding, steadying, and deep downshift.',
    description: 'A Cognistration delta binaural tone for grounding, steadying, and deep downshift.',
    sourceType: 'homepage-generated',
    source_type: 'homepage-generated',
    modeLabel: 'Pure binaural state tone',
    wavUrl: '/audio/homepage-state-tones/delta-cognistration-anchor.wav',
    wav_url: '/audio/homepage-state-tones/delta-cognistration-anchor.wav',
    webmUrl: null,
    webm_url: null,
    mp3Url: null,
    mp3_url: null,
    target_hz: 2.6,
    target_state: 'delta',
    base_freq_hz: 112,
    duration_sec: 60
  },
  {
    id: 'homepage-beta-drive',
    name: 'Beta Drive',
    shortLabel: 'Beta Drive',
    state: 'beta',
    targetState: 'beta',
    targetHz: 17.2,
    baseFreqHz: 286,
    durationSec: 60,
    summary: 'A bare beta binaural tone for execution, task momentum, and alert work.',
    description: 'A bare beta binaural tone for execution, task momentum, and alert work.',
    sourceType: 'homepage-generated',
    source_type: 'homepage-generated',
    modeLabel: 'Pure binaural state tone',
    wavUrl: '/audio/homepage-state-tones/beta-drive.wav',
    wav_url: '/audio/homepage-state-tones/beta-drive.wav',
    webmUrl: null,
    webm_url: null,
    mp3Url: null,
    mp3_url: null,
    target_hz: 17.2,
    target_state: 'beta',
    base_freq_hz: 286,
    duration_sec: 60
  },
  {
    id: 'homepage-gamma-clarity',
    name: 'Gamma Clarity',
    shortLabel: 'Gamma Clarity',
    state: 'gamma',
    targetState: 'gamma',
    targetHz: 39.5,
    baseFreqHz: 392,
    durationSec: 60,
    summary: 'A bare gamma binaural tone for sharpness, synthesis, and high-focus clarity.',
    description: 'A bare gamma binaural tone for sharpness, synthesis, and high-focus clarity.',
    sourceType: 'homepage-generated',
    source_type: 'homepage-generated',
    modeLabel: 'Pure binaural state tone',
    wavUrl: '/audio/homepage-state-tones/gamma-clarity.wav',
    wav_url: '/audio/homepage-state-tones/gamma-clarity.wav',
    webmUrl: null,
    webm_url: null,
    mp3Url: null,
    mp3_url: null,
    target_hz: 39.5,
    target_state: 'gamma',
    base_freq_hz: 392,
    duration_sec: 60
  },
  {
    id: 'homepage-gamma-cognistration-beacon',
    name: 'Cognistration Gamma Beacon',
    shortLabel: 'Gamma Beacon',
    state: 'gamma',
    targetState: 'gamma',
    targetHz: 41.2,
    baseFreqHz: 396,
    durationSec: 60,
    summary: 'A Cognistration gamma binaural tone for synthesis, spark, and crisp high-focus clarity.',
    description: 'A Cognistration gamma binaural tone for synthesis, spark, and crisp high-focus clarity.',
    sourceType: 'homepage-generated',
    source_type: 'homepage-generated',
    modeLabel: 'Pure binaural state tone',
    wavUrl: '/audio/homepage-state-tones/gamma-cognistration-beacon.wav',
    wav_url: '/audio/homepage-state-tones/gamma-cognistration-beacon.wav',
    webmUrl: null,
    webm_url: null,
    mp3Url: null,
    mp3_url: null,
    target_hz: 41.2,
    target_state: 'gamma',
    base_freq_hz: 396,
    duration_sec: 60
  },
  {
    id: 'homepage-theta-liminal-settle',
    name: 'Theta Liminal Settle',
    shortLabel: 'Liminal Settle',
    state: 'theta',
    targetState: 'theta',
    targetHz: 6.1,
    baseFreqHz: 200,
    durationSec: 60,
    summary: 'A steadier theta binaural tone for easing across thresholds without dropping the thread.',
    description: 'A steadier theta binaural tone for easing across thresholds without dropping the thread.',
    sourceType: 'homepage-generated',
    source_type: 'homepage-generated',
    modeLabel: 'Pure binaural state tone',
    wavUrl: '/audio/homepage-state-tones/theta-liminal-settle.wav',
    wav_url: '/audio/homepage-state-tones/theta-liminal-settle.wav',
    webmUrl: null,
    webm_url: null,
    mp3Url: null,
    mp3_url: null,
    target_hz: 6.1,
    target_state: 'theta',
    base_freq_hz: 200,
    duration_sec: 60
  },
  {
    id: 'homepage-theta-quiet-window',
    name: 'Theta Quiet Window',
    shortLabel: 'Quiet Window',
    state: 'theta',
    targetState: 'theta',
    targetHz: 5.7,
    baseFreqHz: 204,
    durationSec: 60,
    summary: 'A gentler theta binaural tone for soft intake, reflective calm, and cognitive settling.',
    description: 'A gentler theta binaural tone for soft intake, reflective calm, and cognitive settling.',
    sourceType: 'homepage-generated',
    source_type: 'homepage-generated',
    modeLabel: 'Pure binaural state tone',
    wavUrl: '/audio/homepage-state-tones/theta-quiet-window.wav',
    wav_url: '/audio/homepage-state-tones/theta-quiet-window.wav',
    webmUrl: null,
    webm_url: null,
    mp3Url: null,
    mp3_url: null,
    target_hz: 5.7,
    target_state: 'theta',
    base_freq_hz: 204,
    duration_sec: 60
  },
  {
    id: 'homepage-alpha-clear-window',
    name: 'Alpha Clear Window',
    shortLabel: 'Clear Window',
    state: 'alpha',
    targetState: 'alpha',
    targetHz: 9.2,
    baseFreqHz: 232,
    durationSec: 60,
    summary: 'A brighter alpha binaural tone for clean focus, composure, and a more open work surface.',
    description: 'A brighter alpha binaural tone for clean focus, composure, and a more open work surface.',
    sourceType: 'homepage-generated',
    source_type: 'homepage-generated',
    modeLabel: 'Pure binaural state tone',
    wavUrl: '/audio/homepage-state-tones/alpha-clear-window.wav',
    wav_url: '/audio/homepage-state-tones/alpha-clear-window.wav',
    webmUrl: null,
    webm_url: null,
    mp3Url: null,
    mp3_url: null,
    target_hz: 9.2,
    target_state: 'alpha',
    base_freq_hz: 232,
    duration_sec: 60
  },
  {
    id: 'homepage-alpha-open-channel',
    name: 'Alpha Open Channel',
    shortLabel: 'Open Channel',
    state: 'alpha',
    targetState: 'alpha',
    targetHz: 8.8,
    baseFreqHz: 228,
    durationSec: 60,
    summary: 'A bright alpha binaural tone for clean signal, responsive focus, and open attention.',
    description: 'A bright alpha binaural tone for clean signal, responsive focus, and open attention.',
    sourceType: 'homepage-generated',
    source_type: 'homepage-generated',
    modeLabel: 'Pure binaural state tone',
    wavUrl: '/audio/homepage-state-tones/alpha-open-channel.wav',
    wav_url: '/audio/homepage-state-tones/alpha-open-channel.wav',
    webmUrl: null,
    webm_url: null,
    mp3Url: null,
    mp3_url: null,
    target_hz: 8.8,
    target_state: 'alpha',
    base_freq_hz: 228,
    duration_sec: 60
  },
  {
    id: 'homepage-theta-cognistration-arc',
    name: 'Cognistration Theta Arc',
    shortLabel: 'Theta Arc',
    state: 'theta',
    targetState: 'theta',
    targetHz: 6.3,
    baseFreqHz: 208,
    durationSec: 60,
    summary: 'A Cognistration theta binaural tone for threshold crossing, reflective calm, and poised intake.',
    description: 'A Cognistration theta binaural tone for threshold crossing, reflective calm, and poised intake.',
    sourceType: 'homepage-generated',
    source_type: 'homepage-generated',
    modeLabel: 'Pure binaural state tone',
    wavUrl: '/audio/homepage-state-tones/theta-cognistration-arc.wav',
    wav_url: '/audio/homepage-state-tones/theta-cognistration-arc.wav',
    webmUrl: null,
    webm_url: null,
    mp3Url: null,
    mp3_url: null,
    target_hz: 6.3,
    target_state: 'theta',
    base_freq_hz: 208,
    duration_sec: 60
  },
  {
    id: 'homepage-theta-cognistration-stillpoint',
    name: 'Cognistration Theta Stillpoint',
    shortLabel: 'Theta Stillpoint',
    state: 'theta',
    targetState: 'theta',
    targetHz: 5.4,
    baseFreqHz: 198,
    durationSec: 60,
    summary: 'A Cognistration theta binaural tone for still attention, threshold ease, and quiet reflection.',
    description: 'A Cognistration theta binaural tone for still attention, threshold ease, and quiet reflection.',
    sourceType: 'homepage-generated',
    source_type: 'homepage-generated',
    modeLabel: 'Pure binaural state tone',
    wavUrl: '/audio/homepage-state-tones/theta-cognistration-stillpoint.wav',
    wav_url: '/audio/homepage-state-tones/theta-cognistration-stillpoint.wav',
    webmUrl: null,
    webm_url: null,
    mp3Url: null,
    mp3_url: null,
    target_hz: 5.4,
    target_state: 'theta',
    base_freq_hz: 198,
    duration_sec: 60
  },
  {
    id: 'homepage-alpha-cognistration-aperture',
    name: 'Cognistration Alpha Aperture',
    shortLabel: 'Alpha Aperture',
    state: 'alpha',
    targetState: 'alpha',
    targetHz: 9.6,
    baseFreqHz: 236,
    durationSec: 60,
    summary: 'A Cognistration alpha binaural tone for clean focus, open attention, and crisp composure.',
    description: 'A Cognistration alpha binaural tone for clean focus, open attention, and crisp composure.',
    sourceType: 'homepage-generated',
    source_type: 'homepage-generated',
    modeLabel: 'Pure binaural state tone',
    wavUrl: '/audio/homepage-state-tones/alpha-cognistration-aperture.wav',
    wav_url: '/audio/homepage-state-tones/alpha-cognistration-aperture.wav',
    webmUrl: null,
    webm_url: null,
    mp3Url: null,
    mp3_url: null,
    target_hz: 9.6,
    target_state: 'alpha',
    base_freq_hz: 236,
    duration_sec: 60
  },
  {
    id: 'homepage-alpha-cognistration-clearline',
    name: 'Cognistration Alpha Clearline',
    shortLabel: 'Alpha Clearline',
    state: 'alpha',
    targetState: 'alpha',
    targetHz: 9.0,
    baseFreqHz: 230,
    durationSec: 60,
    summary: 'A Cognistration alpha binaural tone for clear focus, clean signal, and steady attention.',
    description: 'A Cognistration alpha binaural tone for clear focus, clean signal, and steady attention.',
    sourceType: 'homepage-generated',
    source_type: 'homepage-generated',
    modeLabel: 'Pure binaural state tone',
    wavUrl: '/audio/homepage-state-tones/alpha-cognistration-clearline.wav',
    wav_url: '/audio/homepage-state-tones/alpha-cognistration-clearline.wav',
    webmUrl: null,
    webm_url: null,
    mp3Url: null,
    mp3_url: null,
    target_hz: 9.0,
    target_state: 'alpha',
    base_freq_hz: 230,
    duration_sec: 60
  },
  {
    id: 'homepage-beta-cognistration-pulse',
    name: 'Cognistration Beta Pulse',
    shortLabel: 'Beta Pulse',
    state: 'beta',
    targetState: 'beta',
    targetHz: 18.4,
    baseFreqHz: 292,
    durationSec: 60,
    summary: 'A Cognistration beta binaural tone for forward momentum, task initiation, and steady execution.',
    description: 'A Cognistration beta binaural tone for forward momentum, task initiation, and steady execution.',
    sourceType: 'homepage-generated',
    source_type: 'homepage-generated',
    modeLabel: 'Pure binaural state tone',
    wavUrl: '/audio/homepage-state-tones/beta-cognistration-pulse.wav',
    wav_url: '/audio/homepage-state-tones/beta-cognistration-pulse.wav',
    webmUrl: null,
    webm_url: null,
    mp3Url: null,
    mp3_url: null,
    target_hz: 18.4,
    target_state: 'beta',
    base_freq_hz: 292,
    duration_sec: 60
  },
  {
    id: 'homepage-gamma-cognistration-halo',
    name: 'Cognistration Gamma Halo',
    shortLabel: 'Gamma Halo',
    state: 'gamma',
    targetState: 'gamma',
    targetHz: 42.7,
    baseFreqHz: 404,
    durationSec: 60,
    summary: 'A Cognistration gamma binaural tone for synthesis, bright awareness, and crisp completion.',
    description: 'A Cognistration gamma binaural tone for synthesis, bright awareness, and crisp completion.',
    sourceType: 'homepage-generated',
    source_type: 'homepage-generated',
    modeLabel: 'Pure binaural state tone',
    wavUrl: '/audio/homepage-state-tones/gamma-cognistration-halo.wav',
    wav_url: '/audio/homepage-state-tones/gamma-cognistration-halo.wav',
    webmUrl: null,
    webm_url: null,
    mp3Url: null,
    mp3_url: null,
    target_hz: 42.7,
    target_state: 'gamma',
    base_freq_hz: 404,
    duration_sec: 60
  }
];

export function getHomepageToneById(toneId) {
  return HOMEPAGE_STATE_TONES.find((tone) => tone.id === toneId) || null;
}

export function getHomepageToneByState(state) {
  const normalizedState = String(state || '').toLowerCase();
  return HOMEPAGE_STATE_TONES.find((tone) => tone.state === normalizedState) || null;
}

export function getFeaturedHomepageTone() {
  for (const state of HOMEPAGE_TONE_STATE_ORDER) {
    const tone = getHomepageToneByState(state);
    if (tone) {
      return tone;
    }
  }

  return HOMEPAGE_STATE_TONES[0] || null;
}

export function isHomepageGeneratedTone(tone) {
  return Boolean(tone) && (tone.sourceType === 'homepage-generated' || tone.source_type === 'homepage-generated');
}
