import {
  whyCognistrationFeelsPrivatePostMeta,
  calmFirstSessionSetupPostMeta,
  pulvinarPrecisionBrokerPostMeta,
  reticularStateBrokerPostMeta,
  superiorColliculusOrientingEnginePostMeta,
  cerebellumTimingCompilerPostMeta,
  interoceptivePrecisionArbiterPostMeta,
  locusCoeruleusGainControllerPostMeta,
  predictionErrorRecalibratesRealityPostMeta,
  nestedRhythmsCoordinationLayerPostMeta,
  thalamusPrecisionGovernorPostMeta,
  interoceptiveLoopControlRoomPostMeta,
  vestibularFrameBuilderPostMeta,
  hypnagogiaStateTransitionPostMeta,
  cancellationSignalPostMeta,
  agencyIsAPredictionPostMeta,
  phaseResetCoherentMomentPostMeta,
  bodyMapPresenceDriftPostMeta,
  claustrumAccessPostMeta,
  bodyBoundaryPostMeta,
  consciousnessMechanicsPostMeta,
  posteriorParietalCoordinateEnginePostMeta,
  precuneusContinuityBrokerPostMeta,
  crossFrequencyCouplingPostMeta,
  salienceNetworkPriorityPostMeta,
  memoryReconsolidationPostMeta,
  defaultModeNetworkPostMeta,
  hemisphericCoherencePostMeta,
  interoceptiveBreathPostMeta,
  predictiveCodingPostMeta,
  precisionDecisionPostMeta,
  quietTenMinuteResetPostMeta,
  salienceGatePostMeta,
  sleepGatePostMeta,
  thalamicRouterPostMeta,
  thetaLiminalCorridorPostMeta,
} from "@/lib/blog/posts-data";
import { TheAuditorySystemNeverSleepsPredictableSoundSafetyPostMeta } from "@/lib/blog/posts-data";

export const blogPosts = [
  TheAuditorySystemNeverSleepsPredictableSoundSafetyPostMeta,
  whyCognistrationFeelsPrivatePostMeta,
  calmFirstSessionSetupPostMeta,
  pulvinarPrecisionBrokerPostMeta,
  reticularStateBrokerPostMeta,
  superiorColliculusOrientingEnginePostMeta,
  cerebellumTimingCompilerPostMeta,
  interoceptivePrecisionArbiterPostMeta,
  locusCoeruleusGainControllerPostMeta,
  predictionErrorRecalibratesRealityPostMeta,
  nestedRhythmsCoordinationLayerPostMeta,
  thalamusPrecisionGovernorPostMeta,
  interoceptiveLoopControlRoomPostMeta,
  vestibularFrameBuilderPostMeta,
  hypnagogiaStateTransitionPostMeta,
  cancellationSignalPostMeta,
  agencyIsAPredictionPostMeta,
  phaseResetCoherentMomentPostMeta,
  bodyMapPresenceDriftPostMeta,
  defaultModeNetworkPostMeta,
  claustrumAccessPostMeta,
  bodyBoundaryPostMeta,
  salienceNetworkPriorityPostMeta,
  posteriorParietalCoordinateEnginePostMeta,
  precuneusContinuityBrokerPostMeta,
  crossFrequencyCouplingPostMeta,
  precisionDecisionPostMeta,
  memoryReconsolidationPostMeta,
  thalamicRouterPostMeta,
  salienceGatePostMeta,
  thetaLiminalCorridorPostMeta,
  interoceptiveBreathPostMeta,
  hemisphericCoherencePostMeta,
  sleepGatePostMeta,
  predictiveCodingPostMeta,
  consciousnessMechanicsPostMeta,
  quietTenMinuteResetPostMeta,
];

export function getBlogPostBySlug(slug) {
  return blogPosts.find((post) => post.slug === slug) || null;
}

export function getRecentBlogPosts(limit = 6) {
  return [...blogPosts]
    .sort((a, b) => new Date(b.publishedAt) - new Date(a.publishedAt))
    .slice(0, limit);
}
